#!/bin/bash

if [ "$#" -le 1 ]; then
    echo "Please provide commands to run on a remote host"
    exit 1
fi

REMOTE_HOST=viper
REMOTE_ABSOLUTE_REPO_PATH=/home/said/src/server

ORIG_BRANCH=`git symbolic-ref --short -q HEAD`
echo "creating a temp branch ..."
git checkout -b temp-branch-${REMOTE_HOST}
echo "creating a new remote ..."
git remote add remote-${REMOTE_HOST} ssh://${REMOTE_HOST}${REMOTE_ABSOLUTE_REPO_PATH}
echo "recording a temporary change ..."
git commit -am "temp change"
echo "pushing to ${REMOTE_HOST} ..."
git push remote-${REMOTE_HOST}
echo "running given commands ..."
ssh -A ${REMOTE_HOST} bash << EOF
cd ${REMOTE_ABSOLUTE_REPO_PATH}
echo "checking if staging area is clean ..."
git diff-index --quiet HEAD || { echo "stage on remote host is not clean!"; exit 1;}
git checkout temp-branch-${REMOTE_HOST}
eval "$@"
echo "cleanup ..."
git checkout master
git branch -D temp-branch-${REMOTE_HOST}
EOF
git reset --soft HEAD^1
git checkout ${ORIG_BRANCH}
git branch -D temp-branch-${REMOTE_HOST}
git remote remove remote-${REMOTE_HOST}
